# Generated by Django 5.0.2 on 2024-02-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_comment_options_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
