# Generated by Django 5.0.2 on 2024-02-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/images/user.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
