# Generated by Django 5.0.2 on 2024-02-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/static/users/images/user.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
